<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="565" started-at="2017-10-07T17:36:33Z" finished-at="2017-10-07T17:36:34Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="565" started-at="2017-10-07T17:36:33Z" finished-at="2017-10-07T17:36:34Z">
      <class name="com.test.sample.tests.test1">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="beforeSuite" is-config="true" duration-ms="11092" started-at="2017-10-07T23:06:22Z" finished-at="2017-10-07T23:06:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-10-07T23:06:33Z" finished-at="2017-10-07T23:06:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="test1" duration-ms="356" started-at="2017-10-07T23:06:33Z" finished-at="2017-10-07T23:06:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="aftermethod" is-config="true" duration-ms="16" started-at="2017-10-07T23:06:34Z" finished-at="2017-10-07T23:06:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="test2" duration-ms="3" started-at="2017-10-07T23:06:34Z" finished-at="2017-10-07T23:06:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.sample.tests.test1.test2(test1.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-10-07T23:06:34Z" finished-at="2017-10-07T23:06:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="aftermethod" is-config="true" duration-ms="168" started-at="2017-10-07T23:06:34Z" finished-at="2017-10-07T23:06:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.test.sample.tests.test1@76b10754]" name="afterSuite" is-config="true" duration-ms="9716" started-at="2017-10-07T23:06:34Z" finished-at="2017-10-07T23:06:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.test.sample.tests.test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
